name: Create AMI

on:
  workflow_dispatch:

jobs:
  get-spot-runner:
    environment: aws_dev
    runs-on: ubuntu-latest
    name: Get a spot runner using prod API
    outputs:
      name: ${{ steps.garoclient-spot.outputs.name }}
      runnerstate: ${{ steps.garoclient-spot.outputs.runnerstate }}
      uniqueid: ${{ steps.garoclient-spot.outputs.uniqueid }}
    steps:
      - name: Get runner
        uses: alphagov/github-actions-runner-orchestration/client@main
        id: garoclient-main
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'spot'
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: 'https://prod.co-cdio-garo.digital'
          RUNNER_TIMEOUT: '3600'
          RUNNER_LABEL: 'prod'

      - name: Output runner details
        run: |
          echo "Name: ${{ steps.garoclient-spot.outputs.name }}"
          echo "State: ${{ steps.garoclient-spot.outputs.runnerstate }}"
          echo "UniqueID: ${{ steps.garoclient-spot.outputs.uniqueid }}"

  deploy-to-staging:
    name: Deploy an instance with the build only
    needs: get-spot-runner
    runs-on: [self-hosted, prod, "${{ needs.get-spot-runner.outputs.uniqueid }}"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        cd main/
        export SUBNETID="${{ secrets.RUNNER_SUBNET }}" \
          && export SECURITYG="${{ secrets.RUNNER_SG }}" \
          && scripts/create_ami.sh
