name: Test and deploy to staging and production

on:
  workflow_dispatch:

jobs:
  get-main-deploy-runner:
    environment: aws_dev
    runs-on: ubuntu-latest
    name: Get the main deploy runner using prod API
    outputs:
      name: ${{ steps.garoclient-main.outputs.name }}
      runnerstate: ${{ steps.garoclient-main.outputs.runnerstate }}
      uniqueid: ${{ steps.garoclient-main.outputs.uniqueid }}
    steps:
      - name: Get runner
        uses: alphagov/github-actions-runner-orchestration/client@main
        id: garoclient-main
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'ondemand'
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: 'https://prod.co-cdio-garo.digital'
          RUNNER_TIMEOUT: '3600'
          RUNNER_LABEL: 'prod'

      - name: Output runner details
        run: |
          echo "Name: ${{ steps.garoclient-main.outputs.name }}"
          echo "State: ${{ steps.garoclient-main.outputs.runnerstate }}"
          echo "UniqueID: ${{ steps.garoclient-main.outputs.uniqueid }}"

  deploy-to-staging:
    name: Deploy to staging
    needs: get-main-deploy-runner
    runs-on: [self-hosted, prod, "${{ needs.get-main-deploy-runner.outputs.uniqueid }}"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        source ~/.bash_profile

        nvm install 12.21.0

        cd main/
        make test-full
        make build-full

        cd garo_terraform/
        tfenv install
        tfenv use
        terraform init | awsredact
        terraform validate | awsredact
        terraform workspace list
        terraform workspace select staging
        terraform apply -auto-approve | awsredact

        sleep 5

  get-test-staging-runner:
    name: Start a runner using the staging API
    needs: deploy-to-staging
    environment: aws_dev
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.garoclient-staging-test.outputs.name }}
      runnerstate: ${{ steps.garoclient-staging-test.outputs.runnerstate }}
      uniqueid: ${{ steps.garoclient-staging-test.outputs.uniqueid }}
    steps:
      - name: Get runner
        uses: alphagov/github-actions-runner-orchestration/client@main
        id: garoclient-staging-test
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'spot'
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: 'https://staging.co-cdio-garo.digital'
          RUNNER_TIMEOUT: '900'
          RUNNER_LABEL: 'stagingtest'

      - name: Output runner details
        run: |
          echo "Name: ${{ steps.garoclient-staging-test.outputs.name }}"
          echo "State: ${{ steps.garoclient-staging-test.outputs.runnerstate }}"
          echo "UniqueID: ${{ steps.garoclient-staging-test.outputs.uniqueid }}"

  use-staging-runner:
    name: Test the staging runner
    needs: get-test-staging-runner
    runs-on: [self-hosted, stagingtest, "${{ needs.get-test-staging-runner.outputs.uniqueid }}"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        source ~/.bash_profile
        ls -lah main
        aws sts get-caller-identity | awsredact
        docker run hello-world

  deploy-to-prod:
    name: Deploy to production
    needs: [get-main-deploy-runner, use-staging-runner]
    runs-on: [self-hosted, prod, "${{ needs.get-main-deploy-runner.outputs.uniqueid }}"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        source ~/.bash_profile

        nvm install 12.21.0

        cd main/
        make test-full
        make build-full

        cd garo_terraform/
        tfenv install
        tfenv use
        terraform init | awsredact
        terraform validate | awsredact
        terraform workspace list
        terraform workspace select prod
        terraform apply -auto-approve | awsredact

        sleep 5

  get-test-prod-runner:
    environment: aws_dev
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    name: Start a runner using the prod API
    outputs:
      name: ${{ steps.garoclient-prod-test.outputs.name }}
      runnerstate: ${{ steps.garoclient-prod-test.outputs.runnerstate }}
      uniqueid: ${{ steps.garoclient-prod-test.outputs.uniqueid }}
    steps:
      - name: Get runner
        uses: alphagov/github-actions-runner-orchestration/client@main
        id: garoclient-prod-test
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'spot'
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: 'https://prod.co-cdio-garo.digital'
          RUNNER_TIMEOUT: '900'
          RUNNER_LABEL: 'prodtest'

      - name: Output runner details
        run: |
          echo "Name: ${{ steps.garoclient-prod-test.outputs.name }}"
          echo "State: ${{ steps.garoclient-prod-test.outputs.runnerstate }}"
          echo "UniqueID: ${{ steps.garoclient-prod-test.outputs.uniqueid }}"

  use-prod-runner:
    name: Test the production runner
    needs: get-test-prod-runner
    runs-on: [self-hosted, prodtest, "${{ needs.get-test-prod-runner.outputs.uniqueid }}"]
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - run: |
        source ~/.bash_profile
        ls -lah main
        aws sts get-caller-identity | awsredact
        docker run hello-world
