name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  get-runners:
    environment: aws_dev
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - label: test1
          type: spot
        - label: test2
          type: spot
        - label: test3
          type: ondemand
    steps:
      - name: Get Runner
        uses: alphagov/github-actions-runner-orchestration/client@main
        id: garoclient
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: ${{ matrix.type }}
          RUNNER_LABEL: ${{ matrix.label }}
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: 'https://dev.co-cdio-garo.digital'
          RUNNER_TIMEOUT: '900'

  use-test1-runner:
    runs-on: [self-hosted, linux, spot, test1]
    needs: get-runners
    defaults:
      run:
        shell: bash
    steps:
    - run: |
        source ~/.bash_profile
        echo "Hello world from test1!"
        echo ""
        aws sts get-caller-identity
        echo ""

  use-test2-runner:
    runs-on: [self-hosted, linux, spot, test2]
    needs: get-runners
    defaults:
      run:
        shell: bash
    steps:
    - run: |
        source ~/.bash_profile
        echo "Hello world from test2!"
        echo ""
        aws sts get-caller-identity
        echo ""

  use-test3-runner:
    runs-on: [self-hosted, linux, ondemand, test3]
    needs: get-runners
    defaults:
      run:
        shell: bash
    steps:
    - run: |
        source ~/.bash_profile
        echo "Hello world from test3 (ondemand)!"
        echo ""
        aws sts get-caller-identity
        echo ""
