name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test the runners
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Runner
        uses: ./client # Uses an action in the root directory
        id: garo-client
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'spot'
          REPO: 'alphagov/github-actions-runner-orchestration'
          GITHUB_COMMIT: '$GITHUB_SHA'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }'
          GARO_URL: '${{ secrets.RUNNER_URL }}'

      - name: Get the output runner name
        run: echo "The time was ${{ steps.garo-client.outputs.name }}"
