name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  get-runner:
    environment: personal_test
    runs-on: ubuntu-latest
    name: A job to test the runners
    outputs:
      name: ${{ steps.garoclient.outputs.name }}
      runnerstate: ${{ steps.garoclient.outputs.runnerstate }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Runner
        uses: ./client # Uses an action in the root directory
        id: garoclient
        with:
          ACTION: 'start'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          RUNNER_TYPE: 'spot'
          REPO: '${{ github.repository }}'
          GITHUB_COMMIT: '${{ github.sha }}'
          RUNNER_SUBNET: '${{ secrets.RUNNER_SUBNET }}'
          RUNNER_SG: '${{ secrets.RUNNER_SG }}'
          RUNNER_ACID: '${{ secrets.RUNNER_ACID }}'
          RUNNER_EXID: '${{ secrets.RUNNER_EXID }}'
          GARO_URL: '${{ secrets.GARO_URL }}'

      - name: Output runner details
        run: |
          echo "Name ${{ steps.garoclient.outputs.name }}"
          echo "Name ${{ steps.garoclient.outputs.runnerstate }}"
  use-runner:
    runs-on: [self-hosted, linux, spot]
    needs: get-runner
    steps:
    - run: |
        echo "Hello world!"
        echo ""
        aws sts get-caller-identity

        echo "Runner name: ${{ needs.get-runner.outputs.name }}"
        echo "Runner name: ${{ needs.get-runner.outputs.runnerstate }}"
        echo ""
